[parity]
chain = "/openethereum/genesis.json" 
base_path = "/openethereum/" 

[network]
port = 30306
reserved_peers=  "/openethereum/nodes" 
allow_ips = "all"
discovery = false

[rpc]
port = 8548
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces" ,"rpc", "parity_accounts"]
interface = "all"
cors = ["all"]

[websockets]
disable = false
port = 10546
interface = "all"
origins = ["none"]
apis = ["all"]
hosts = ["all"]

[account]
password = ["/openethereum/password"] 

[mining]
engine_signer = "0x27f91dafa072771f4bc2bed30b46b16219f9e6c3"  
gas_floor_target = "40000000"

[misc]
logging = "own_tx=trace"
log_file = "/openethereum/log.log"
color = true
