[parity]
chain = "/openethereum/genesis.json" 
base_path = "/openethereum/" 

[network]
port = 30307
reserved_peers=  "/openethereum/nodes" 
allow_ips = "all"
# Override the bootnodes from selected chain file.
#bootnodes = ["enode://XXX@localhost:30300", "enode://XXXX@localhost:30301"]
# Enable or disable new peers discovery.
discovery = true

[rpc]
port = 8549
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces" ,"rpc", "parity_accounts"]
interface = "all"
cors = ["all"]

[websockets]
disable = false
port = 10548
interface = "all"
origins = ["none"]
apis = ["all"]
hosts = ["all"]

[account]
password = ["/openethereum/password"] 

[mining]
engine_signer = "0x6624688a9294571ea8376f2ba26c4fd450a5c1ab"  
gas_floor_target = "40000000"

[misc]
logging = "own_tx=trace"
log_file = "/openethereum/log.log"
color = true
