version: "3.4"

services:

  pos1:
    image: "nara7875/openethereum:pos1"
    tty: true
    ports:
      - 8547:8547
      - 30305:30305
      - 10546:10546
    environment:
      ENV: ETHERNODE1
      RPCPORT: 8547
      PORT: 30305
      RUST_BACKTRACE: 1
    volumes:
      - ./config1.toml:/openethereum/config.toml
      - ./genesis1.json:/openethereum/genesis.json
      - ./password:/openethereum/password
      - ./nodes:/openethereum/nodes
      - ./keys1:/openethereum/keys
    container_name: pos1
    command: >
      sh -c "cd ~/
            /openethereum/target/release/openethereum --config /openethereum/config.toml"
    working_dir: /openethereum


  pos2:
    image: "nara7875/openethereum:pos2"
    tty: true
    ports:
      - 8548:8548
      - 30306:30306
      - 10547:10547
    environment:
      ENV: ETHERNODE1
      RPCPORT: 8548
      PORT: 30306
      RUST_BACKTRACE: 1
    volumes:
      - ./config2.toml:/openethereum/config.toml
      - ./genesis2.json:/openethereum/genesis.json
      - ./password:/openethereum/password
      - ./nodes:/openethereum/nodes
      - ./keys2:/openethereum/keys
    container_name: pos2
    command: >
      sh -c "cd ~/
            /openethereum/target/release/openethereum --config /openethereum/config.toml"
    working_dir: /openethereum

  pos3:
    image: "nara7875/openethereum:pos3"
    tty: true
    ports:
      - 8549:8549
      - 30307:30307
      - 10548:10548
    environment:
      ENV: ETHERNODE1
      RPCPORT: 8549
      PORT: 30307
      RUST_BACKTRACE: 1
    volumes:
      - ./config3.toml:/openethereum/config.toml
      - ./genesis3.json:/openethereum/genesis.json
      - ./password:/openethereum/password
      - ./keys3:/openethereum/keys
      - ./nodes:/openethereum/nodes
    container_name: pos3
    command: >
      sh -c "cd ~/
            /openethereum/target/release/openethereum --config /openethereum/config.toml"
    working_dir: /openethereum

  # pos4:
  #   image: "nara7875/openethereum:pos4"
  #   tty: true
  #   ports:
  #     - 8550:8550
  #     - 30308:30308
  #     - 10549:10549
  #   environment:
  #     ENV: ETHERNODE1
  #     RPCPORT: 8550
  #     PORT: 30308
  #     RUST_BACKTRACE: 1
  #   volumes:
  #     - ./config4.toml:/openethereum/config.toml
  #     - ./genesis4.json:/openethereum/genesis.json
  #     - ./password:/openethereum/password
  #     - ./nodes:/openethereum/nodes
  #     - ./keys4:/openethereum/keys
  #   container_name: pos4
  #   command: >
  #     sh -c "cd ~/
  #           /openethereum/target/release/openethereum --config /openethereum/config.toml"
  #   working_dir: /openethereum
  poscli:
    image: "nara7875/openethereum:0"
    tty: true
    container_name: pos-cli
    working_dir: /openethereum
    command: /bin/bash
 
    links:
      - pos1:pos1
      - pos2:pos2
      - pos3:pos3
      # - pos4:pos4
    
    depends_on:
      - pos1
      - pos2
      - pos3
      # - pos4
  entry1:
    image: "nara7875/etcexplorer:1"
    ports:
      - 3001:3000
    restart: always
    depends_on:
      - db
    # links:
    #   - pos1:pos1
    volumes:
      - ./config1.json:/config.json
      - ./ACT1.png:/public/img/explorer-logo.png
      - ./explorer1/favicon.ico:/public/favicon.ico
    environment:
      MONGO_URI: mongodb://host.docker.internal/ACT
    command : bash -c "/wait-for-it.sh -h mongo -p 27017 -t 20 -- npm run start"
  
  entry2:
    image: "nara7875/etcexplorer:1"
    ports:
      - 3002:3000
    restart: always
    depends_on:
      - db
    # links:
    #   - pos2:pos2
    volumes:
      - ./config2.json:/config.json
      - ./GGOM.png:/public/img/explorer-logo.png
      - ./explorer1/favicon.ico:/public/favicon.ico
    environment:
      MONGO_URI: mongodb://host.docker.internal/GGOM
    command : bash -c "/wait-for-it.sh -h mongo -p 27017 -t 20 -- npm run start"
  
  entry3:
    image: "nara7875/etcexplorer:1"
    ports:
      - 3003:3000
    restart: always
    depends_on:
      - db
    # links:
    #   - pos3:pos3
    volumes:
      - ./config3.json:/config.json
      - ./ONE.png:/public/img/explorer-logo.png
      - ./explorer1/favicon.ico:/public/favicon.ico
    environment:
      MONGO_URI: mongodb://host.docker.internal/ONE
    command : bash -c "/wait-for-it.sh -h mongo -p 27017 -t 20 -- npm run start"
  
  # entry4:
  #   image: "nara7875/etcexplorer:1"
  #   ports:
  #     - 3004:3000
  #   restart: always
  #   depends_on:
  #     - db
  #   # links:
  #   #   - pos4:pos4
  #   volumes:
  #     - ./config4.json:/config.json
  #     - ./HEINI1.png:/public/img/explorer-logo.png
  #     - ./explorer1/favicon.ico:/public/favicon.ico
  #   environment:
  #     MONGO_URI: mongodb://host.docker.internal/HEINI
  #   command : bash -c "/wait-for-it.sh -h mongo -p 27017 -t 20 -- npm run start"
  
  db:
    image: "mongo"
    ports: 
      - 27017:27017
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_DATABASE: "[ACT, GGOM, HEINI, ONE]"



  